config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
  resources :users, except: [:new]      #`new` is handled by signup route

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, :presence => true, :length => {:minimum => 5, :maximum => 50}
  validates :description, :presence => true, :length => {:minimum => 10, :maximum => 200}

end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :articles, dependent: :destroy

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: {:minimum => 3, :maximum => 25}
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: {:maximum => 105}, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]    #only runs if the object is not previously set
  end

  def logged_in?
    !!current_user     #changes into boolean
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    
    def index
        @articles = Article.order(created_at: :desc).all
    end

    def show
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(params.require(:article).permit(:title, :description))
        @article.user = current_user
        if @article.valid?
            @article.save
            flash[:notice] = "Article was created successfully"
            redirect_to @article
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(params.require(:article).permit(:title, :description))
            flash[:notice] = "Article is updated successfully"
            redirect_to @article
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        if @article.destroy
            flash[:alert] = "The article was deleted"
            redirect_to articles_path
        end
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def require_same_user
        if current_user != @article.user
            flash[:alert] = "You can only edit or delete your own article"
            redirect_to @article
        end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end

    def about 
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged In Successfully."
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @articles = @user.articles
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(params.require(:user).permit(:username, :email, :password))
      flash[:notice] = "Your account information is successfully updated"
      redirect_to user_path(@user)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @user = User.new(params.require(:user).permit(:username, :email, :password))
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully signed up !"
      redirect_to user_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    flash[:alert] = "Account is deleted along with its all associated articles"
    redirect_to articles_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user !=  @user
      flash[:alert] = "You can only edit your own profile"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articles-list.html.erb
<% @articles.each do |article| %>
  <div class="container", style="margin-top: 30px">
    <div class="card">
      <div class="card-header">
        <%= article.title %>
      </div>
      <div class="card-body">
        <h5 class="card-title"> <%= article.description %> </h5>
        <p class="card-text"> <i>By: <%= article.user.username %></i>  </p>
        <!--        <a href="#" class="btn btn-primary">See more</a>-->
        <%= link_to "Show", article_path(article), method: :show, class: "btn btn-primary" %>
        <% if logged_in? && article.user == current_user %>
          <%= link_to "Edit", edit_article_path(article), method: :edit, class: "btn btn-secondary" %>
          <%= link_to "Delete", article_path(article), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article%>

<%=  form_with(model: @article, local: true) do |f| %>

  <div class="container">
    <div class=" card" style="margin-top: 30px">
      <h5 class="card-header"> Article Details </h5>
      <div class="card-body">
        <form>
          <div class="form-group">
            <p>
              <%= f.label :title %>
              <%= f.text_field :title, class:"form-control", placeholder: "Enter title" %>
            </p>

            <p>
              <%= f.label :description %>
              <%= f.text_area :description, class:"form-control", placeholder: "Enter description" %>
            </p>

            <p>
              <%= f.submit "Submit Article", class: "btn btn-primary" %> <%= link_to "Cancel", articles_path, class: "btn btn-outline-danger" %>
            </p>
          </div>
        </form>
      </div>
    </div>
  </div>

<% end %>




<%#=  form_with scope: :article, url: articles_path, local: true do |f| %>

<!--  <p>-->
<!--    <%#= f.label :title %> <br/>-->
    <%#= f.text_field :title %>
<!--  </p>-->

<!--  <p>-->
<!--    <%#= f.label :description %> <br/>-->
    <%#= f.text_area :description %>
<!--  </p>-->


<!--  <p>-->
    <%#= f.submit %>
<!--  </p>-->

<%# end %>

app/views/articles/edit.html.erb
<h2 class="heading", style="text-align: center; margin-top: 20px"> Aritcles editing page </h2>
<%= render 'form' %>

app/views/articles/index.html.erb
<h2 class="heading", style="text-align: center; margin-top: 20px"> Aritcles listing page </h2>

<%= render 'articles-list' %>

app/views/articles/new.html.erb
<h2 class="heading", style="text-align: center; margin-top: 20px"> Aritcles creating page </h2>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="heading", style="text-align: center; margin-top: 20px">Showing Article Details </h2>

<div class="container", style="margin-top: 30px">
  <div class="card">
    <div class="card-header">
      <%= @article.title %>
    </div>
    <div class="card-body">
      <h5 class="card-title"> <%= @article.description %> </h5>
      <p class="card-text"> <i>By: <%= @article.user.username %></i>  </p>
      <!--        <a href="#" class="btn btn-primary">See more</a>-->
      <%#= link_to "Back", articles_path, class: "btn btn-outline-primary" %>
      <% if logged_in? && @article.user == current_user %>
        <%= link_to "Edit", edit_article_path(@article), method: :edit, class: "btn btn-secondary" %>
        <%= link_to "Delete", article_path(@article), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_flash_msg.html.erb
<% flash.each do |name, msg| %>

  <% if name == "alert" %>
    <div class="class alert alert-danger" role="alert" >
    <%= msg %>
    </div>
  <% elsif name == "notice" %>
    <div class="class alert alert-success" role="alert" >
      <%= msg %>
    </div>
  <% end %>

<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!--      <a class="navbar-brand" href="#">Navbar</a>-->
  <%= link_to "HOME", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <!--          <li class="nav-item ">-->
      <!--            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
      <%#= link_to "Articles", articles_path, class: "nav-link active" %>
      <!--          </li>-->

<!--      <li class="nav-item">-->
<!--        <a class="nav-link" href="#">Link</a>-->

        <%#= link_to "About", about_path, class: "nav-link" %>
<!--      </li>-->
      <li class="nav-item">
        <!--            <a class="nav-link " href="#" tabindex="-1" aria-disabled="true">Bloggers</a>-->
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <!--              <a class="dropdown-item" href="#">Action</a>-->
          <%= link_to "View Articles", articles_path, class: "dropdown-item" %>
          <!--              <a class="dropdown-item" href="#">Another action</a>-->
          <% if logged_in?%>
            <%= link_to "Create New", new_article_path, class: "dropdown-item" %>
          <% end %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <% if !logged_in? %>
        <li class="nav-item">
          <%= link_to "Log In", login_path, class: "nav-link text-success" %>
        </li>
      <% else %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <!--              <a class="dropdown-item" href="#">Action</a>-->
            <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
            <!--              <a class="dropdown-item" href="#">Another action</a>-->
            <%= link_to "Create Article", new_article_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Delete Account", user_path(current_user), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "dropdown-item text-danger"  %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", logout_path, class: "nav-link", method: :delete %>
        </li>
      <% end %>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>

  <body>

    <%= render "layouts/navigation" %>


    <%=  render "layouts/flash_msg" %>

    <%= yield %>

<!--    To prevent footer from blocking content -->
    <div style="height: 80px; background-color: transparent"></div>

    <!-- Writing CSS style here, because bootstrap not set up properly -->
    <footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50",
            style="
              display: flex;
              align-items: center;
              font-size:20px;
              color:white;
              position: fixed;
              bottom: 0;
              width: 100%;
              height: 50px
            "
    >
      <div class="container text-center">
        <small>Copyright &copy; Article Blog</small>
      </div>
    </footer>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

app/views/pages/about.html.erb
<h2 class="heading", style="text-align: center; margin-top: 20px"> About Us </h2>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <div class="container">
    <div class="jumbotron",
          style="
            margin-top: 30px;
            background-image: url('https://images.unsplash.com/photo-1522881451255-f59ad836fdfb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1572&q=80');
            background-size: cover;
            height: 400px;
            width: 100%
         "
    >
        <h1 style="color: white">Articles Blog</h1>
        <p style="color: antiquewhite">Welcome to the Article Blog </p>
      <br><br>
        <p>
<!--          <a class="btn btn-primary btn-lg" href="#" role="button">Sign Up</a>-->
          <%= link_to "Sign Up", signup_path, class: "btn btn-primary btn-lg" %>
        </p>
    </div>
    </div>


</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container", style="margin-top: 30px">
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong>The following errors prevented the <%= obj.class.name.downcase %> from being saved</strong>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user%>

<%=  form_with(model: @user, local: true) do |f| %>
  <div class="container">
    <div class=" card" style="margin-top: 30px">
      <h5 class="card-header">Account Details</h5>
      <div class="card-body">
        <form>
          <div class="form-group">
            <p>
              <%= f.label :username %>
              <%= f.text_field :username, class:"form-control", placeholder: "Enter username" %>
            </p>

            <p>
              <%= f.label :email %>
              <%= f.email_field :email, class:"form-control", placeholder: "Enter email" %>
            </p>

            <p>
              <%= f.label :password %>
              <%= f.password_field :password, class:"form-control", placeholder: "Enter password" %>
            </p>

            <p>
              <%= f.submit(@user.new_record? ? "Sign Up" : "Update account", class: "btn btn-primary") %>
              <%= link_to "Cancel", @user, class: "btn btn-outline-danger" %>
            </p>
          </div>
        </form>
      </div>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<h2 class="heading", style="text-align: center; margin-top: 20px"> Edit you profile </h2>
<%= render 'form' %>

app/views/users/index.html.erb
<h2 class="heading", style="text-align: center; margin-top: 20px"> Bloggers </h2>

<% @users.each do |user| %>
  <div class="container", style="margin-top: 30px">
    <div class="card">
      <div class="card-header">
        <%= user.username %>
      </div>
      <div class="card-body">
        <div style="text-align: center">
          <img src="https://picsum.photos/200" style="position:relative; float: left; margin-right: 20px" />
        </div>

        <p class="card-text"> <i><%= pluralize(user.articles.count, "article") %> </i>  </p>
        <!--        <a href="#" class="btn btn-primary">See more</a>-->
        <%= link_to "View", user_path(user), method: :show, class: "btn btn-outline-success" %>
        <% if logged_in? && user == current_user %>
          <%= link_to "Edit", edit_user_path(user), method: :edit, class: "btn btn-outline-secondary" %>
          <%#= link_to "Delete", user_path(user), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<h2 class="heading", style="text-align: center; margin-top: 20px"> Sign Up </h2>
<%= render 'form' %>

app/views/users/show.html.erb
<h2 class="heading", style="text-align: center; margin-top: 20px"> <%= @user.username %>'s profile </h2>
<br>
<div style="text-align: center">
  <img src="https://picsum.photos/200"  />
</div>
<br>
<div style="text-align: center">
  <% if logged_in? && @user == current_user %>
    <%= link_to "Update Profile", edit_user_path(@user), method: :edit, class: "btn btn-outline-primary" %>
    <%= link_to "Create Article", new_article_path, method: :new, class: "btn btn-outline-success" %>
  <% end %>
</div>


<%= render 'articles/articles-list' %>